<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        \DB::table('item_details')->delete();

        \DB::table('item_details')->insert(array (
            0 =>
            array (
                'id' => 1,
                'item_id' => 1003,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '1 year',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 1,
                'is_cash_on_delivery' => 1,
                'tax_id' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'item_id' => 1004,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '1 year',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 1,
                'is_cash_on_delivery' => 1,
                'tax_id' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'item_id' => 1005,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '11 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'item_id' => 1006,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '5 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'item_id' => 1007,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '1 year',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 1,
                'tax_id' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'item_id' => 1008,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '7 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 1,
                'is_featured' => 1,
                'is_cash_on_delivery' => 1,
                'tax_id' => NULL,
            ),
            6 =>
            array (
                'id' => 8,
                'item_id' => 1010,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '2 years',
                'warranty_policy' => 'szd',
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            7 =>
            array (
                'id' => 9,
                'item_id' => 1011,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '3 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            8 =>
            array (
                'id' => 10,
                'item_id' => 1012,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '2 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 1,
                'is_featured' => 0,
                'is_cash_on_delivery' => 1,
                'tax_id' => Null,
            ),
            9 =>
            array (
                'id' => 11,
                'item_id' => 1013,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => '1 year',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            10 =>
            array (
                'id' => 12,
                'item_id' => 1014,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '5 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 1,
                'tax_id' => NULL,
            ),
            11 =>
            array (
                'id' => 15,
                'item_id' => 1017,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '9 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            12 =>
            array (
                'id' => 16,
                'item_id' => 1018,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '2 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            13 =>
            array (
                'id' => 17,
                'item_id' => 1019,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            14 =>
            array (
                'id' => 18,
                'item_id' => 1020,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            15 =>
            array (
                'id' => 19,
                'item_id' => 1021,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            16 =>
            array (
                'id' => 20,
                'item_id' => 1022,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            17 =>
            array (
                'id' => 21,
                'item_id' => 1023,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            18 =>
            array (
                'id' => 22,
                'item_id' => 1024,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            19 =>
            array (
                'id' => 23,
                'item_id' => 1025,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            20 =>
            array (
                'id' => 24,
                'item_id' => 1026,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => '4 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            21 =>
            array (
                'id' => 25,
                'item_id' => 1027,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            22 =>
            array (
                'id' => 26,
                'item_id' => 1028,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => '4 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            23 =>
            array (
                'id' => 27,
                'item_id' => 1029,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => '10 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            24 =>
            array (
                'id' => 28,
                'item_id' => 1030,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            25 =>
            array (
                'id' => 29,
                'item_id' => 1031,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => 'Lifetime',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            26 =>
            array (
                'id' => 30,
                'item_id' => 1032,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '12 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            27 =>
            array (
                'id' => 31,
                'item_id' => 1033,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '4 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            28 =>
            array (
                'id' => 32,
                'item_id' => 1034,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '5 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            29 =>
            array (
                'id' => 33,
                'item_id' => 1035,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '3 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            30 =>
            array (
                'id' => 34,
                'item_id' => 1036,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '3 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            31 =>
            array (
                'id' => 35,
                'item_id' => 1037,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => 'Lifetime',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            32 =>
            array (
                'id' => 36,
                'item_id' => 1038,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => 'Lifetime',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            33 =>
            array (
                'id' => 37,
                'item_id' => 1039,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '8 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            34 =>
            array (
                'id' => 38,
                'item_id' => 1040,
                'warranty_type' => 'Seller Warranty',
                'warranty_period' => '3 years',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            35 =>
            array (
                'id' => 39,
                'item_id' => 1041,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '8 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            36 =>
            array (
                'id' => 40,
                'item_id' => 1042,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '9 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            37 =>
            array (
                'id' => 41,
                'item_id' => 1043,
                'warranty_type' => 'Brand Warranty',
                'warranty_period' => '3 months',
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            38 =>
            array (
                'id' => 42,
                'item_id' => 1044,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            39 =>
            array (
                'id' => 43,
                'item_id' => 1001,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            40 =>
            array (
                'id' => 44,
                'item_id' => 1002,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            41 =>
            array (
                'id' => 45,
                'item_id' => 1046,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            42 =>
            array (
                'id' => 46,
                'item_id' => 1048,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
            43 =>
            array (
                'id' => 47,
                'item_id' => 1047,
                'warranty_type' => 'No Warranty',
                'warranty_period' => NULL,
                'warranty_policy' => NULL,
                'shipping_id' => 1,
                'is_track_inventory' => 0,
                'is_hide_stock' => 0,
                'is_featured' => 0,
                'is_cash_on_delivery' => 0,
                'tax_id' => NULL,
            ),
        ));

        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
