<?php

namespace Modules\MenuBuilder\Database\Seeders;

use Illuminate\Database\Seeder;

class AdminMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('menu_items')->delete();

        \DB::table('menu_items')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'label' => 'dashboard',
                    'link' => 'dashboard',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\DashboardController@index","route_name":["dashboard"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-home',
                    'parent' => 0,
                    'sort' => 0,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            1 =>
                array (
                    'id' => 2,
                    'label' => 'user-list',
                    'link' => 'user/list',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\UserController@index","route_name":["users.index","users.create","users.edit","users.import","users.pdf","users.csv","users.verify","users.profile"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 27,
                    'sort' => 2,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            2 =>
                array (
                    'id' => 3,
                    'label' => 'items',
                    'link' => 'items',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\ItemController@index","route_name":["item.index","item.create","item.edit","item.pdf","item.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 4,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            3 =>
                array (
                    'id' => 4,
                    'label' => 'brands',
                    'link' => 'brands',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\BrandController@index","route_name":["brands.index","brands.create","brands.edit","brands.pdf","brands.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 5,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            4 =>
                array (
                    'id' => 5,
                    'label' => 'categories',
                    'link' => 'categories',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\CategoryController@index","route_name":["categories.index"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 7,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            5 =>
                array (
                    'id' => 6,
                    'label' => 'attributes',
                    'link' => 'attributes',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\AttributeController@index","route_name":["attribute.index","attribute.create","attribute.edit","attribute.pdf","attribute.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 6,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            6 =>
                array (
                    'id' => 7,
                    'label' => 'attribute-groups',
                    'link' => 'attribute-groups',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\AttributeGroupController@index","route_name":["attributeGroup.index","attributeGroup.create","attributeGroup.edit","attributeGroup.pdf","attributeGroup.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 8,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            7 =>
                array (
                    'id' => 8,
                    'label' => 'options',
                    'link' => 'options',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\OptionController@index","route_name":["option.index","option.create","option.edit","option.pdf","option.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 9,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            8 =>
                array (
                    'id' => 9,
                    'label' => 'reviews',
                    'link' => 'reviews',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\ReviewController@index","route_name":["review.index","review.view","review.edit","review.pdf","review.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 28,
                    'sort' => 10,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            9 =>
                array (
                    'id' => 10,
                    'label' => 'packages',
                    'link' => 'package',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\PackageController@index","route_name":["package.index","package.create","package.edit","package.pdf","package.csv"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 29,
                    'sort' => 14,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            10 =>
                array (
                    'id' => 11,
                    'label' => 'package-subscription',
                    'link' => 'package-subscription',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\PackageSubscriptionController@index","route_name":["packageSubscription.index","packageSubscription.create","packageSubscription.edit","packageSubscription.pdf","packageSubscription.csv","packageSubscription.show"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 29,
                    'sort' => 15,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            12 =>
                array (
                    'id' => 13,
                    'label' => 'vendors',
                    'link' => 'vendors',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Api\\\\VendorController@index","route_name":["vendors.index","vendors.create","vendors.edit","vendors.pdf","vendors.csv","vendors.import"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 30,
                    'sort' => 18,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            13 =>
                array (
                    'id' => 14,
                    'label' => 'addons',
                    'link' => 'addons',
                    'params' => '{"permission":"Modules\\\\Addons\\\\Http\\\\Controllers\\\\AddonsController@index","route_name":["addon.index","addon.switch-status","addon.remove","addon.upload"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-chess-rook',
                    'parent' => 0,
                    'sort' => 20,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            14 =>
                array (
                    'id' => 15,
                    'label' => 'coupons',
                    'link' => 'coupons',
                    'params' => '{"permission":"Modules\\\\Coupon\\\\Http\\\\Controllers\\\\CouponController@index","route_name":["coupon.index","coupon.create","coupon.edit","coupon.pdf","coupon.csv","coupon.shop","coupon.item","couponRedeem.index","couponRedeem.pdf","couponRedeem.csv"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-ticket-alt',
                    'parent' => 0,
                    'sort' => 21,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            15 =>
                array (
                    'id' => 16,
                    'label' => 'menu-builder',
                    'link' => 'menu-builder',
                    'params' => '{"permission":"Modules\\\\Addons\\\\Http\\\\Controllers\\\\AddonsController@index","route_name":["addon.index","addon.switch-status","addon.remove","addon.upload"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-bars',
                    'parent' => 0,
                    'sort' => 24,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            16 =>
                array (
                    'id' => 17,
                    'label' => 'shop',
                    'link' => 'shop',
                    'params' => '{"permission":"Modules\\\\Shop\\\\Http\\\\Controllers\\\\ShopController@index","route_name":["shop.index","shop.create","shop.edit","shop.pdf","shop.csv","shopPdf.pdf","shopCsv.csv"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-archive',
                    'parent' => 0,
                    'sort' => 22,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            17 =>
                array (
                    'id' => 18,
                    'label' => 'company-details',
                    'link' => 'company/setting',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\CompanySettingController@index","route_name":["companyDetails.setting"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 27,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            18 =>
                array (
                    'id' => 19,
                    'label' => 'general-settings',
                    'link' => 'emailConfiguration',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\EmailConfigurationController@index","route_name":["emailConfigurations.index", "maintenance.enable", "smsConfiguration.index", "language.translation", "language.index", "currency.convert", "sso.index", "orderStatues.index"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 26,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            19 =>
                array (
                    'id' => 20,
                    'label' => 'finance',
                    'link' => 'currencies',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\CurrencyController@index","route_name":["currency.index","validCurrencyName", "paymentTerm.index", "paymentTerm.edit", "tax.index", "tax.edit"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 28,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            20 =>
                array (
                    'id' => 21,
                    'label' => 'email-templates',
                    'link' => 'emailTemplate/list',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\MailTemplateController@index", "route_name":["emailTemplates.index", "emailTemplates.create", "emailTemplates.edit"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 29,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            21 =>
                array (
                    'id' => 22,
                    'label' => 'sms-templates',
                    'link' => 'smsTemplate/list',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\SmsTemplateController@index","route_name":["smsTemplates.index", "smsTemplates.create", "smsTemplates.edit"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 30,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            22 =>
                array (
                    'id' => 23,
                    'label' => 'preference',
                    'link' => 'preference',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\PreferenceController@index","route_name":["preferences.index","preferences.theme"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 31,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            23 =>
                array (
                    'id' => 24,
                    'label' => 'roles',
                    'link' => 'role/list',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\RoleController@index","route_name":["roles.index","roles.create","roles.edit"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 32,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            24 =>
                array (
                    'id' => 25,
                    'label' => 'permission-role',
                    'link' => 'permission-role',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\PermissionRoleController@index","route_name":["permissionRoles.index","generatePermission.index"]}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 31,
                    'sort' => 33,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            25 =>
                array (
                    'id' => 26,
                    'label' => 'cache-clear',
                    'link' => 'clear-cache',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\DashboardController@index","route_name":["clear-cache"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-trash-alt',
                    'parent' => 0,
                    'sort' => 34,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            26 =>
                array (
                    'id' => 27,
                    'label' => 'Personnel',
                    'link' => NULL,
                    'params' => NULL,
                    'is_default' => 0,
                    'icon' => 'fas fa-users',
                    'parent' => 0,
                    'sort' => 1,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            27 =>
                array (
                    'id' => 28,
                    'label' => 'Items',
                    'link' => 'Items main',
                    'params' => NULL,
                    'is_default' => 0,
                    'icon' => 'fas fa-database',
                    'parent' => 0,
                    'sort' => 3,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            28 =>
                array (
                    'id' => 29,
                    'label' => 'Manage Billings',
                    'link' => NULL,
                    'params' => NULL,
                    'is_default' => 0,
                    'icon' => 'fas fa-money-bill-alt',
                    'parent' => 0,
                    'sort' => 13,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            29 =>
                array (
                    'id' => 30,
                    'label' => 'Vendors',
                    'link' => NULL,
                    'params' => NULL,
                    'is_default' => 0,
                    'icon' => 'fas fa-universal-access',
                    'parent' => 0,
                    'sort' => 17,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            30 =>
                array (
                    'id' => 31,
                    'label' => 'Configarations',
                    'link' => NULL,
                    'params' => NULL,
                    'is_default' => 0,
                    'icon' => 'fas fa-cog',
                    'parent' => 0,
                    'sort' => 25,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            31 =>
                array (
                    'id' => 32,
                    'label' => 'dashboard',
                    'link' => 'dashboard',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\DashboardController@index","route_name":["site.dashboard"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-align-justify',
                    'parent' => 0,
                    'sort' => 0,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            32 =>
                array (
                    'id' => 33,
                    'label' => 'orders',
                    'link' => 'orders',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\OrderController@index","route_name":["site.order"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fab fa-apple',
                    'parent' => 0,
                    'sort' => 1,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            33 =>
                array (
                    'id' => 34,
                    'label' => 'wishlist',
                    'link' => 'wishlists',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\WishlistController@index","route_name":["site.wishlist"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'far fa-heart',
                    'parent' => 0,
                    'sort' => 2,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            34 =>
                array (
                    'id' => 35,
                    'label' => 'review',
                    'link' => 'reviews',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\ReviewController@index","route_name":["site.review"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-certificate',
                    'parent' => 0,
                    'sort' => 3,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            35 =>
                array (
                    'id' => 36,
                    'label' => 'user-profile',
                    'link' => 'profile',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\UserController@index","route_name":["site.userProfile","site.userProfileEditPassword"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-user',
                    'parent' => 0,
                    'sort' => 4,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            36 =>
                array (
                    'id' => 37,
                    'label' => 'address-books',
                    'link' => 'addresses',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\AddressController@index","route_name":["site.address","site.addressCreate","site.addressEdit"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-phone',
                    'parent' => 0,
                    'sort' => 5,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            37 =>
                array (
                    'id' => 38,
                    'label' => 'settings',
                    'link' => 'setting',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\AddressController@index","route_name":["site.userSetting"],"menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-cog',
                    'parent' => 0,
                    'sort' => 6,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            38 =>
                array (
                    'id' => 39,
                    'label' => 'Logout',
                    'link' => 'logout',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Site\\\\LoginController@logout", "route_name":["site.logout"], "menu_level":"2"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-sign-out-alt',
                    'parent' => 0,
                    'sort' => 7,
                    'class' => NULL,
                    'menu' => 2,
                    'depth' => 0,
                ),
            39 =>
                array (
                    'id' => 40,
                    'label' => 'dashboard',
                    'link' => 'dashboard',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\VendorController@index","route_name":["vendor-dashboard"],"menu_level":"3"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-database',
                    'parent' => 0,
                    'sort' => 0,
                    'class' => NULL,
                    'menu' => 3,
                    'depth' => 0,
                ),
            40 =>
                array (
                    'id' => 41,
                    'label' => 'my-subscription',
                    'link' => 'my-subscription',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\MySubscriptionController@index","route_name":["vendor.my_subscription.index","vendor.my_subscription.pricing","vendor.payment.index","vendor.renew"],"menu_level":"3"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-life-ring',
                    'parent' => 0,
                    'sort' => 1,
                    'class' => NULL,
                    'menu' => 3,
                    'depth' => 0,
                ),
            41 =>
                array (
                    'id' => 42,
                    'label' => 'all-orders',
                    'link' => 'orders',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\AdminOrderController@index", "route_name":["order.index", "order.view", "order.pdf", "order.csv"], "menu_level":"1"}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 43,
                    'sort' => 12,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            42 =>
                array (
                    'id' => 43,
                    'label' => 'Sales',
                    'link' => NULL,
                    'params' => NULL,
                    'is_default' => 0,
                    'icon' => 'fas fa-dollar-sign',
                    'parent' => 0,
                    'sort' => 11,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            43 =>
                array (
                    'id' => 45,
                    'label' => 'shipping',
                    'link' => 'shippings',
                    'params' => '{"permission":"Modules\\\\Shipping\\\\Http\\\\Controllers\\\\ShippingController@index","route_name":["shipping.index","shipping.create","shipping.store","shipping.edit","shipping.update","shipping.delete"]}',
                    'is_default' => 1,
                    'icon' => 'fas fa-shipping-fast',
                    'parent' => 0,
                    'sort' => 23,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 0,
                ),
            44 =>
                array (
                    'id' => 46,
                    'label' => 'wallet',
                    'link' => 'wallets',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorWalletController@index","route_name":["vendorWallet.index"]}',
                    'is_default' => 1,
                    'icon' => 'far fa-credit-card',
                    'parent' => 0,
                    'sort' => 3,
                    'class' => NULL,
                    'menu' => 3,
                    'depth' => 0,
                ),
            45 =>
                array (
                    'id' => 47,
                    'label' => 'commission',
                    'link' => 'commission',
                    'params' => '{"permission":"Modules\\\\Commission\\\\Http\\\\Controllers\\\\CommissionController@index", "route_name":["commission.index"], "menu_level":"1"}',
                    'is_default' => 1,
                    'icon' => NULL,
                    'parent' => 30,
                    'sort' => 19,
                    'class' => NULL,
                    'menu' => 1,
                    'depth' => 1,
                ),
            46 =>
                array (
                    'id' => 48,
                    'label' => 'Orders',
                    'link' => 'orders',
                    'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorOrderController@index", "route_name":["vendorOrder.index", "vendorOrder.view", "vendorOrder.pdf", "vendorOrder.csv"], "menu_level":"3"}',
                    'is_default' => 1,
                    'icon' => 'fas fa-dollar-sign',
                    'parent' => 0,
                    'sort' => 2,
                    'class' => NULL,
                    'menu' => 3,
                    'depth' => 0,
                ),
        ));




    }
}
